version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

    # Ignore TypeScript >= 5.9.0
    ignore:
      - dependency-name: "typescript"
        versions: [">=5.9.0"]
